name: supabase_quickstart
description: Sample app on how to get started with Supabase on Flutter. 

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.8.5
  supabase_flutter: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  uses-material-design: true